"""Lyric ↔ story resonance — the keyed build side (LLM pass).

For each event, take its story (summary Overview + conclusion) and its theme song's
lyrics (fetched live via ``source/lyrics.py``) and write a short note on how the song
resonates with the event's arc/ending. Results land in ``resonance_cache.json`` and
are served keyless by the resonance intent (phase 4).

**Provider-agnostic.** The LLM call is an injected ``generate(prompt) -> str`` so the
same pass runs on Gemini (``sekai resonance``), a local model, or — while we wait on
Google credits — Claude subagents driven from the main session. The cache is
fingerprinted on **content only** (Overview + conclusion + lyrics + prompt version),
NOT the model, so entries generated by one backend are honored by another and nothing
regenerates just because the model changed.

**Copyright.** Lyrics are fetched live and never persisted; the note must paraphrase /
reference imagery, not reproduce lyric passages. Only the derived note + the source
attribution are cached.
"""

from __future__ import annotations

import json
import os
from collections.abc import Callable
from typing import Any

from ..console import safe_print
from .manifest import stable_hash

RESONANCE_CACHE_SCHEMA_VERSION = "1"
RESONANCE_PROMPT_VERSION = "1"

RESONANCE_SYSTEM_INSTRUCTIONS = (
    "You analyze how a Project Sekai event's theme song resonates with its story. "
    "You are given the event's story overview, how it ends, and the theme song's "
    "lyrics (Japanese + English). Write a focused note (2-4 sentences) on how the "
    "song mirrors the event's emotional arc and resolution — connect specific lyric "
    "imagery/themes to specific story beats and the ending.\n\n"
    "Rules: paraphrase or reference at most a SHORT phrase of the lyrics — never "
    "reproduce lines or stanzas (the lyrics are copyrighted and not rehosted). No "
    "preamble ('In this event…'), no plot recap for its own sake — only the "
    "song↔story connection. If the lyrics don't clearly connect, say so briefly."
)


def build_resonance_input(
    name: str, song_title: str, overview: str, conclusion: str, lyrics_text: str
) -> str:
    """Assemble the user prompt (pure). Kept small: Overview + conclusion + lyrics."""
    return (
        f"Event: {name}\n"
        f"Theme song: {song_title}\n\n"
        f"Story overview:\n{overview}\n\n"
        f"How it ends:\n{conclusion}\n\n"
        f"Theme song lyrics (Japanese / English):\n{lyrics_text}"
    )


def resonance_fingerprint(overview: str, conclusion: str, lyrics_text: str) -> str:
    """Content-only fingerprint — deliberately excludes model/provider so Claude- and
    Gemini-generated notes coexist and don't churn on a backend switch."""
    return stable_hash(
        {
            "schema_version": RESONANCE_CACHE_SCHEMA_VERSION,
            "prompt_version": RESONANCE_PROMPT_VERSION,
            "overview": overview,
            "conclusion": conclusion,
            "lyrics": lyrics_text,
        }
    )


def load_cache(cache_file: str) -> dict[str, Any]:
    if not os.path.exists(cache_file):
        return {}
    with open(cache_file, encoding="utf-8") as fh:
        loaded = json.load(fh)
    return loaded if isinstance(loaded, dict) else {}


def save_cache(cache_file: str, cache: dict[str, Any]) -> None:
    with open(cache_file, "w", encoding="utf-8") as fh:
        json.dump(cache, fh, ensure_ascii=False, indent=2)


def store_resonance(
    cache: dict[str, Any], arc: str, *, note: str, fingerprint: str,
    model: str, attribution: str = "",
) -> None:
    """Write one entry keyed ``EVENT|<arc>`` (shared by the CLI + the subagent bootstrap)."""
    cache[f"EVENT|{arc}"] = {
        "schema_version": RESONANCE_CACHE_SCHEMA_VERSION,
        "fingerprint": fingerprint,
        "resonance": note.strip(),
        "model": model,
        "attribution": attribution,
    }


def _summary_text(entry: Any) -> str:
    if isinstance(entry, dict):
        return entry.get("summary") or ""
    return entry if isinstance(entry, str) else ""


def assemble_resonance_inputs(
    events_index: list[dict],
    summaries: dict[str, Any],
    page_map: dict[str, Any],
    *,
    conclusions: dict[str, Any] | None = None,
    arcs: set[str] | None = None,
    limit: int = 0,
    fetch: Callable[[int, dict], dict | None] | None = None,
) -> list[dict]:
    """Build resonance inputs for events that have a summary AND a mapped song with
    fetchable lyrics. Conclusion comes from ``conclusions`` cache when present, else
    the keyless heuristic. ``fetch`` defaults to the live Sekaipedia lyric fetch
    (inject a stub in tests). Skips (logs) events missing any piece."""
    from ..query.conclusion import derive_conclusion
    from ..source import lyrics as lyrics_mod
    from .summary_sections import extract_summary_sections

    fetch = fetch or lyrics_mod.fetch_lyrics
    out: list[dict] = []
    for ev in events_index:
        arc, song_id = ev.get("arc_slug"), ev.get("song_id")
        if not arc or not isinstance(song_id, int):
            continue
        if arcs is not None and arc not in arcs:
            continue
        summary = _summary_text(summaries.get(f"EVENT|{arc}"))
        if not summary.strip():
            continue
        overview = extract_summary_sections(summary).get("Overview") or summary
        concl_entry = (conclusions or {}).get(f"EVENT|{arc}")
        if isinstance(concl_entry, dict) and concl_entry.get("conclusion"):
            conclusion = concl_entry["conclusion"]
        else:
            conclusion = derive_conclusion(summary, name=ev.get("name", ""))
        lyrics = fetch(song_id, page_map)
        if not lyrics or not lyrics.get("lines"):
            continue
        # Standardized English song name (never the JP title): wiki `english`, else
        # the wiki page name, else — as a last resort — the JP master-DB title.
        entry = page_map.get(str(song_id), {})
        song_title = entry.get("english") or entry.get("title") or ev.get("song_title", "")
        out.append({
            "arc": arc,
            "name": ev.get("name", ""),
            "song_title": song_title,
            "overview": overview.strip(),
            "conclusion": conclusion.strip(),
            "lyrics_text": lyrics_mod.lyrics_to_text(lyrics["lines"]),
            "attribution": lyrics.get("attribution", ""),
        })
        if limit and len(out) >= limit:
            break
    return out


class ResonanceExtractor:
    """Runs the resonance pass over pre-assembled per-event inputs with an injected
    ``generate``. Fingerprint-cached + resumable, mirroring the conclusions pass."""

    def __init__(self, generate: Callable[[str], str], *, model: str = ""):
        self.generate = generate
        self.model = model

    def extract(
        self,
        inputs: list[dict],
        cache_file: str = "resonance_cache.json",
        *,
        limit: int = 0,
        skip_existing: bool = False,
    ) -> dict[str, Any]:
        """``inputs``: ``[{arc, name, song_title, overview, conclusion, lyrics_text,
        attribution}]``. ``limit`` (>0) stops after that many NEW notes; ``skip_existing``
        keeps an existing entry even if its fingerprint changed."""
        cache = load_cache(cache_file)
        generated = 0
        for item in inputs:
            arc = item["arc"]
            key = f"EVENT|{arc}"
            fp = resonance_fingerprint(
                item["overview"], item["conclusion"], item["lyrics_text"]
            )
            existing = cache.get(key)
            if isinstance(existing, dict) and existing.get("fingerprint") == fp:
                safe_print(f"Loading cached resonance for {key}...")
                continue
            if isinstance(existing, dict) and skip_existing:
                safe_print(f"Keeping existing {key} (--skip-existing).")
                continue
            if limit and generated >= limit:
                safe_print(f"Reached --limit {limit}; stopping before {key}.")
                break
            safe_print(f"Resonance for {key}...")
            note = self.generate(
                build_resonance_input(
                    item["name"], item["song_title"], item["overview"],
                    item["conclusion"], item["lyrics_text"],
                )
            )
            store_resonance(
                cache, arc, note=note, fingerprint=fp, model=self.model,
                attribution=item.get("attribution", ""),
            )
            generated += 1
            save_cache(cache_file, cache)
        return cache
